### ISSUE TITLE
Channel for Talk

### ISSUE THREAD

**Issue by ghost** [rodlie/draco#17]
Hi @rodlie my name is Alfonso by which of the means we can talk? IRC Telegram or how?

**Comment by rodlie** [comment]
I created https://t.me/dracolinuxorg some time ago, never used it...

**Comment by ghost** [comment]
I think that is a news channel but not a group to talk

**Comment by ghost** [comment]
or give me you username and I'm looking for you

**Comment by rodlie** [comment]
fixed.
