### ISSUE TITLE
Fusion proposal with the Astian Foundation

### ISSUE THREAD

**Issue by ghost** [rodlie/draco#24]
Hello @rodlie 

A few days have passed since we talked and made the proposal to merge the project with the Astian Foundation, in these days we have done Slackware tests, that the installation is a little delayed by the construction and configuration but after this, Draco works wonders It is beautiful very very light, in Ubuntu we also do tests with some things to improve and report. in Fedora I work half machine, in OpenSUSE I'm testing it right now.

After this I can conclude that the desktop is wow is powerful, it is wonderful is incredible and we are very motivated to make the fusion, and work in conjunction with this desktop that has a lot of potential.

@rodlie  Tell us what have you thought?

**Comment by rodlie** [comment]
Hi, been busy with work this week, also had issues with my broadband. I will contact you on Sunday/Monday.

**Comment by ghost** [comment]
Ok Excellent Thanks Rodlie
