### ISSUE TITLE
Edit menus

### ISSUE THREAD

**Issue by cwilling** [rodlie/draco#27]
How may I edit the main window context menu (mouse button 3)?

**Comment by FrostKnight** [comment]
I have been trying to figure that out myself too... :100:

**Comment by rodlie** [comment]
Not possible at the moment.

What are the needs? Custom actions or just a .desktop?

**Comment by cwilling** [comment]
I'd like to add apps e.g. xterm which I use a lot. It's a bit tedious always having to navigate down from the main App menu to find them. Since you mention .desktop files, I've added xterm.desktop to the desktop itself. That works OK actually but it would still be better having it available from the context menu.

**Comment by rodlie** [comment]
Ok.

**Comment by rodlie** [comment]
custom menu can be done in ~/.config/draco/desktopsettings.conf
```
[menu]
itemlist=applications,windowlist,settings/wallpaper,app::::/home/olear/.local/share/applications/org.qt-project.qtcreator.desktop
```
