### ISSUE TITLE
Feature Request: Build with QT_NO_DBUS

### ISSUE THREAD

**Issue by FrostKnight** [rodlie/draco#28]
Hello,
I would like to be able to run this desktop environment without D-Bus, it appears several #ifdef would be needed to make this happen.
I've confirmed it is currently possible to run Lumina without D-Bus, but I very much would like to use draco instead.

Thank you.
Btw, all I am asking is you make an option so that you can disable it, you don't have to completely gut it out.  Dbus apparently fingerprints you.

https://redmine.tails.boum.org/code/issues/7100

**Comment by rodlie** [comment]
Maybe .... But you will loose anything power/storage related.



Btw, machine-id can easily be changed etc... No big issue IMHO.

**Comment by FrostKnight** [comment]
You mean powerkit right? What storage would I lose out of curiosity?

Regardless, let me know when you are able to make a test version. 

Btw, thank you for being receptive to my request.  

Edit: I just noticed what you meant regarding  storage and power by reading the docs,

If its possible, I would like suspend, lock and shutdown to be available without dbus, my distro wants to completely gut dbus because it is so bloated. That's why I make this request.    So yeah, is it possible to use upower directly to do power related stuff? 

But yeah, even if you can make a no dbus option, that would be lovely.  

I guess to sum it up, is it possible to make powerkit and draco desktop have a no dbus option?

I will gladly test whatever you come up with. :)

**Comment by rodlie** [comment]
Powerkit and several other things was merged into Draco, so D-Bus is integrated deeply into the Desktop, but I can probably add an option to build without.

The power stuff requires D-Bus as we do all communication using that bus. At the moment I don't know of any better way to handle root access to various hardware.

Anyway, I will look into this.

**Comment by FrostKnight** [comment]
> Powerkit and several other things was merged into Draco, so D-Bus is integrated deeply into the Desktop, but I can probably add an option to build without.
> 
> The power stuff requires D-Bus as we do all communication using that bus. At the moment I don't know of any better way to handle root access to various hardware.
> 
> Anyway, I will look into this.

Much appreciated.

**Comment by rodlie** [comment]
The ``wip`` branch can now be built without D-Bus support (-DDBUS_SUPPORT=OFF), it still needs some fixes before I merge into master, feel free to test.

**Comment by FrostKnight** [comment]
Is building from make... Trying it out right now...

Yes! It works.  The only thing that didn't show up was the power manager.  So its all in all a good test. :)

Well, besides other minor issues anyways.  But yeah, it is quite stable.

Editing, it seems power and storage are the last hurdles?

Anyways I appreciate this. Thank you.

**Comment by FrostKnight** [comment]
Thank you for all the work you did regarding this, I thank you very much, I will hold on to this version of your draco desktop in case others want it, but I will close for now if thats ok, I am using i3-wm as mentioned here: 
https://github.com/rodlie/powerkit/issues/29#issuecomment-649746803
