### ISSUE TITLE
How to log into a draco session on Ubuntu?

### ISSUE THREAD

**Issue by probonopd** [rodlie/draco#31]
Running on a Xubuntu 18.04 Live ISO, draco compiles but I was unable to log into a session using it... any help appreciated.

```
sudo apt-get -y install git tree build-essential cmake pkg-config qtbase5-dev libqt5x11extras5-dev libx11-dev libxss-dev libxdamage-dev libxrandr-dev libxfixes-dev libxcb1-dev libx11-xcb-dev libxcb-randr0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-composite0-dev libxcb-damage0-dev libxcb-util0-dev libxcb-shm0-dev openbox-dev openbox

git clone https://github.com/rodlie/draco
cd draco/
mkdir build && cd build

sudo rm -rf /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5Gui_QWaylandEglPlatformIntegrationPlugin.cmake
sudo rm /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5Gui_QWaylandIntegrationPlugin.cmake
sudo rm /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5Gui_QWaylandXCompositeEglPlatformIntegrationPlugin.cmake
sudo rm /usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5Gui_QWaylandXCompositeGlxPlatformIntegrationPlugin.cmake 

cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBEXECDIR=bin -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc)
sudo make install
sudo cp -r /usr/lib64/libDraco* /usr/lib/x86_64-linux-gnu/
```

Log out -> Choose draco session -> Log in -> (Still logs into Xfce...)

**Comment by rodlie** [comment]
Probably an issue with the login manager not finding the config or something. Been a while since I tested on Ubuntu, I can do a test on Xubuntu 18.04 later tonight/tomorrow.

**Comment by rodlie** [comment]
didn't see that you have the Draco session option. Maybe you are missing a required runtime dependency.

**Comment by probonopd** [comment]
Can you give me a hint on how to go about debugging this? Thank you very much.

**Comment by rodlie** [comment]
Should be an output to console if something failed.

try running startdraco from the console (without the login manager)

**Comment by probonopd** [comment]
After logging out and trying to log in using the Draco session, `sudo grep -r -i draco /var/log/` doesn't show anything. 

Running from within Xfce:

```
me@host:~$ start-draco 
Window manager not found!
```

**Comment by rodlie** [comment]
install openbox.

**Comment by probonopd** [comment]
Thanks. How could I have missed that piece.

Now 

```
me@host:~$ start-draco 
```

works from within an existing Xfce session, but when I choose "Draco" from the login window (where one enters username and password) still the Xfce session is launched. (I cannot exclude the possibility that this may have to do with the fact that I am running from a Xubuntu Live ISO.)

**Comment by probonopd** [comment]
Yes, I think that is what happening - whatever I choose, I am _always_ logged into a Xubuntu session. Sorry for the noise, most definitely not a Draco issue. Still I'd be thankful if you have some ideas on where to start debugging this. My bet is on something in 

```
me@host:~$ ls /etc/X11/Xsession.d/
20dbus_xdg-runtime              60x11-common_xdg_path
20x11-common_process-args       60xbrlapi
30x11-common_xresources         70gconfd_path-on-session
35x11-common_xhost-local        70im-config_launch
40x11-common_xsessionrc         75dbus_dbus-launch
50x11-common_determine-startup  90gpg-agent
55numlockx                      90qt-a11y
55xfce4-session                 90x11-common_ssh-agent
56xubuntu-session               95dbus_update-activation-env
60x11-common_localhost          99x11-common_start
```

The obvious file there seems to be "harmless" though? 

```
me@host:~$ cat /etc/X11/Xsession.d/56xubuntu-session
# Set default environment vars in Xubuntu
if [ "$DESKTOP_SESSION" = xubuntu ]; then
    # Disable GTK 3.16 overlay scrollbars
    export GTK_OVERLAY_SCROLLING=0
    # QT5 apps to use GTK style
    export QT_QPA_PLATFORMTHEME=gtk2
    # Workaround clutter issue (LP: #1462445)
    export CLUTTER_BACKEND=x11
fi
```

Need to find out what sets, and what potentially messes with, `$DESKTOP_SESSION`...

Grepping for it shows that I have

```
me@host:~$ ls -lh /etc/X11/xinit/
total 5.5K
-rwxr-xr-x 1 root root 164 Jan 31  2018 xinitrc
-rw-r--r-- 1 root root 631 May  8 22:38 xinitrc.draco
-rw-r--r-- 1 root root 134 Dec 23  2017 xinputrc
-rwxr-xr-x 1 root root  46 Jan 31  2018 xserverrc
```
Is `xinitrc.draco` supposed to replace `xinitrc`?


```
sudo mv /etc/X11/xinit/xinitrc /etc/X11/xinit/xinitrc.xubuntu
sudo mv /etc/X11/xinit/xinitrc.draco /etc/X11/xinit/xinitrc
```

No, that's not it. Logging out, trying to log into the Draco session -> Does not make a difference. Somehow my system seems to be hardwired to always log into a Xubuntu session, no matter what.

```
me@host:~$ ls /usr/share/xsessions/
draco.desktop  fluxbox.desktop  openbox.desktop  xfce.desktop  xubuntu.desktop

me@host:~$ cat ~/.xsession
cat: /home/me/.xsession: No such file or directory
```

For extra kicks, I am now installing `nodm` and choose it instead of the default `lightdm` to see what happens.

**Comment by probonopd** [comment]
> For extra kicks, I am now installing `nodm` and choose it instead of the default `lightdm` to see what happens.

After also doing sudo apt-get -y remove 'xfce-*' it now drops me into openbox...

Maybe `/etc/alternatives/x-session-manager` has to dio with it.

**Comment by probonopd** [comment]
> For extra kicks, I am now installing `nodm` and choose it instead of the default `lightdm` to see what happens.

After also doing `sudo apt-get -y remove 'xfce-*'` it now drops me into plain openbox...

Maybe `/etc/alternatives/x-session-manager` has to do with it?

**Comment by probonopd** [comment]
New day, new luck. Starting from a freshly booted Xubuntu 18.04 Live ISO.

`/etc/X11/xinit/xinitrc.draco` never gets run. Why? What is supposed to call it?

`me@host:~$ sudo mv /etc/X11/xinit/xinitrc* .` seems to result in no change at all, apparently those files are not used at all.

**Comment by probonopd** [comment]
```
me@host:~$ sudo update-alternatives --config x-session-manager
There are 3 choices for the alternative x-session-manager (providing /usr/bin/x-session-manager).

  Selection    Path                      Priority   Status
------------------------------------------------------------
* 0            /usr/bin/startxfce4        50        auto mode
  1            /usr/bin/openbox-session   40        manual mode
  2            /usr/bin/startxfce4        50        manual mode
  3            /usr/bin/xfce4-session     40        manual mode
```

No draco in here...

```
me@host:~$ ls -lh /usr/bin/x-session-manager
lrwxrwxrwx 1 root root 35 Feb  3 19:34 /usr/bin/x-session-manager -> /etc/alternatives/x-session-manager
me@host:~$ ls -lh /etc/alternatives/x-session-manager
lrwxrwxrwx 1 root root 19 May  9 09:46 /etc/alternatives/x-session-manager -> /usr/bin/startxfce4
```

Changing this:

```
me@host:~$ sudo update-alternatives --config x-session-manager
There are 3 choices for the alternative x-session-manager (providing /usr/bin/x-session-manager).

  Selection    Path                      Priority   Status
------------------------------------------------------------
* 0            /usr/bin/startxfce4        50        auto mode
  1            /usr/bin/openbox-session   40        manual mode
  2            /usr/bin/startxfce4        50        manual mode
  3            /usr/bin/xfce4-session     40        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/bin/openbox-session to provide /usr/bin/x-session-manager (x-session-manager) in manual mode
me@host:~$ ls -lh /etc/alternatives/x-session-manager
lrwxrwxrwx 1 root root 24 May  9 09:46 /etc/alternatives/x-session-manager -> /usr/bin/openbox-session
```

Changing this to option 1 does not seem to make any difference whatsoever.

That in turn runs `/usr/lib/x86_64-linux-gnu/openbox-autostart` which runs `/usr/lib/x86_64-linux-gnu/openbox-xdg-autostart`. `/etc/xdg/openbox/autostart` is empty.

**Comment by rodlie** [comment]
Your system probably don't support xinit anymore? See /usr/share/xsessions/openbox.desktop, will probably need to make one for Draco. I can fix this later today.

**Comment by probonopd** [comment]
```
me@host:~$ cat /usr/share/xsessions/openbox.desktop
[Desktop Entry]
Name=Openbox
Comment=Log in using the Openbox window manager (without a session manager)
Exec=/usr/bin/openbox-session
TryExec=/usr/bin/openbox-session
Icon=openbox
Type=Application
```

There is also one for Draco:

```
me@host:~$ cat /usr/share/xsessions/draco.desktop 
[Desktop Entry]
Exec=start-draco
TryExec=start-draco
Icon=system-run
Type=Application
Name=Draco
Comment=Draco Desktop Environment
```

Maybe it doesn't get used or there is something wrong about its contents?

**Comment by rodlie** [comment]
Ah, yeah I already added that one some time ago....I know I tested it against the default login manager in Ubuntu (gdm?), and it worked.

**Comment by probonopd** [comment]
If with "login manager" you mean the "display manager", it's `lightdm` in the case of Xfce. But yesterday I had replaced it with `nodm` and found no way to make it log into Draco. (Have since rebooted the Live ISO to revert to a "normal" setup.) I have to say that regardless of which session I choose in lightdm, I always land in a Xubuntu desktop, so it's driving me nuts but it's most likely not Draco's fault. :)

**Comment by rodlie** [comment]
ligthdm should work, it reads from /usr/share/xsessions/*.desktop. nodm should use (or be aware of) the /etc/X11/xinit/xinitrc file (that can be symlinked to xinitrc.draco).

Another option to bypass everything:
```
ln -sf /etc/X11/xinit/xinitrc.draco ~/.xsession
```

I will download the live iso and test for myself (sometime today).

**Comment by probonopd** [comment]
`ln -sf /etc/X11/xinit/xinitrc.draco ~/.xsession` results in no change. Thanks for your patience with me.

**Comment by probonopd** [comment]
I have no `/etc/X11/xinit/xinitrc.draco`.

```
me@host:~$ sudo find /etc/ | grep xinitrc
/etc/xdg/xfce4/xinitrc
```

So I did:

```
sudo cp ./draco/share/xinit/xinitrc.draco /etc/X11/xinit/
ln -sf /etc/X11/xinit/xinitrc.draco ~/.xsession
```

No change either.

Thanks for being patient with me.

**Comment by rodlie** [comment]
the file needs to be executable, but where is Draco installed? /usr/local?

**Comment by probonopd** [comment]
```
me@host:~$ ls -lh ~/.xsession
lrwxrwxrwx 1 me me 28 May  9 10:43 /home/me/.xsession -> /etc/X11/xinit/xinitrc.draco

me@host:~$ ls -lh  /etc/X11/xinit/xinitrc.draco
-rwxr-xr-x 1 root root 631 May  9 10:42 /etc/X11/xinit/xinitrc.draco

me@host:~$ which start-draco 
/usr/bin/start-draco

me@host:~$ which draco-settings
/usr/bin/draco-settings
```

**Comment by rodlie** [comment]
https://www.linuxquestions.org/questions/linux-software-2/nodm-display-manager-doesn%27t-start-x-in-my-system-4175519447/#post5241477

**Comment by probonopd** [comment]
While logged into the Xubuntu session that I seemingly can't get rid of, the values are:

```
me@host:~$ env | grep SESSION
XDG_SESSION_ID=c19
DESKTOP_SESSION=xubuntu
XDG_SESSION_TYPE=x11
XDG_SESSION_DESKTOP=xubuntu
GDMSESSION=xubuntu
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/999/bus
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session9
SESSION_MANAGER=local/host:@/tmp/.ICE-unix/8256,unix/host:/tmp/.ICE-unix/8256
```

So, seemingly no `NODM_XSESSION` is causing me to be locked into Xfce...

Question to self, how can I unset

```
XDG_SESSION_DESKTOP=xubuntu
GDMSESSION=xubuntu
```

when `lightdm` is being used...

`dbus-update-activation-environment` seems to have to do with it. Possibly `/etc/X11/Xsession.d/20dbus_xdg-runtime` and/or `/etc/X11/Xsession.d/95dbus_update-activation-env`.

**Comment by probonopd** [comment]
Yay! Moving away `/etc/X11/Xsession.d/20dbus_xdg-runtime` and `/etc/X11/Xsession.d/95dbus_update-activation-env` now lets me log into a Draco session! :+1:

**Comment by probonopd** [comment]
Which packages do they belong to, and what are those packages doing after all?

`dbus-user-session` and `dbus-x11`:

```
me@host:~$ dpkg -S /etc/X11/Xsession.d/20dbus_xdg-runtime
dbus-user-session: /etc/X11/Xsession.d/20dbus_xdg-runtime

me@host:~$ dpkg -S /etc/X11/Xsession.d/95dbus_update-activation-env
dbus-x11: /etc/X11/Xsession.d/95dbus_update-activation-env
```

**Comment by probonopd** [comment]
Strange. With my experimental deb it works out of the box with no further fiddling around needed. Hence closing here. Thanks for your hints!
