### ISSUE TITLE
All applications appear on the desktop?

### ISSUE THREAD

**Issue by probonopd** [rodlie/draco#36]
Feature or bug?

![](https://user-images.githubusercontent.com/2480569/81469475-88a79600-91d4-11ea-9bd4-97f14cab22e5.png)

**Comment by rodlie** [comment]
Only item in ~/Desktop should show.

**Comment by probonopd** [comment]
Confirmed, for some weird reason those got placed into `~/Desktop` which should not happen but must be my fault in https://github.com/probonopd/go-appimage - they are supposed to go to `~/.local/share/applications/` only...

**Comment by probonopd** [comment]
There is something funny going on... even if I stop `appimaged`, and then install applications using `apt-get`, their icons appear on the desktop. It is almost as if something would symlink desktop files automatically into `~/Desktop`...

```
me@host:~$ ls -lh ~/Desktop
total 8.0K
lrwxrwxrwx 1 me   me     39 May  9 11:25 pnmixer.desktop -> /usr/share/applications/pnmixer.desktop
lrwxrwxrwx 1 me   me     41 May  9 11:23 qterminal.desktop -> /usr/share/applications/qterminal.desktop
lrwxrwxrwx 1 me   me     46 May  9 11:23 qterminal_drop.desktop -> /usr/share/applications/qterminal_drop.desktop
```

**Comment by rodlie** [comment]
Look at the settings ;) default is to add "new" applications to the desktop.

**Comment by probonopd** [comment]
I see, `AutomaticDesktopAppLinks`. Thanks!

Note to self: `./.config/draco/pluginsettings/desktopsettings.conf`, `generateDesktopIcons=true` is responsible for doing this. Which is possibly a good idea in general but incompatible to the way `appimaged` works.

**Comment by rodlie** [comment]
I could make this feature disabled as default, it's not something I use personally.
