### ISSUE TITLE
Change font and theme

### ISSUE THREAD

**Issue by probonopd** [rodlie/draco#48]
* How fixed are the choices: Adwaita icon theme and DejaVu font. Would you be open for other suggestions for the default theme and font?
* Alternatively: Is there a way to use something else than the Adwaita theme and the DejaVu font without having to recompile?

**Comment by probonopd** [comment]
QtFM already allows to use a custom fallback icon theme:

![old](https://user-images.githubusercontent.com/2480569/81498007-d8a85a80-92b1-11ea-8fd6-da0d45346c39.png)

![new](https://user-images.githubusercontent.com/2480569/81498006-d80fc400-92b1-11ea-87fc-8bf38f097d89.png)

**Comment by rodlie** [comment]
Theming is controlled by qt5ct, you can use whatever you want ...

https://github.com/rodlie/draco/blob/master/share/theme/qt5ct.conf

**Comment by probonopd** [comment]
`qt5ct` always felt "non-native" to me. Will have to check it out again. 

Note to self: Reading more about it, it seems like it provides a Qt Platform Abstraction (QPA). Does it not use qxcb then?

**Comment by probonopd** [comment]
`qt5ct` is great. It even lets one switch the order of the buttons in a dialog box ("Dialog buttons layout!) like so:

![](https://user-images.githubusercontent.com/2480569/81508618-9fdda500-92f4-11ea-855e-93fb343b841c.png)
