### ISSUE TITLE
Is it possible to use the draco desktop environment in node-os?

### ISSUE THREAD

**Issue by ghost** [rodlie/draco#51]
Hi all! 

Is it possible to use the draco desktop environment in [node-os](https://github.com/NodeOS/NodeOS)?

**Comment by rodlie** [comment]
Hi,

if it provide the required dependencies and runtimes, probably.

Note that this desktop environment is currently unmaintained.

**Comment by ghost** [comment]
Hi! 

If this project is abandoned or no longer maintained. It is worth taking a look at the [abandonware](https://github.com/abandonware) organization that is responsible for developing, maintaining abandoned or no longer maintained projects. *"abandonware - This organization aims to provide community co-maintenance of orphan projects."*

**Note:** I like this project, please don't delete it. If possible send this project to [abandonware](https://github.com/abandonware), someone can help maintain it if you can't maintain this project.
